build:
	go build -o calendar cmd/calendar/main.go

test:
	go test -v -count=1 -race -timeout=30s ./...

install:
	go mod download

install-deps:
	go install github.com/golangci/golangci-lint/cmd/golangci-lint

lint: install-deps
	golangci-lint run ./...

migrate:
	goose -dir migrations/ postgres "host=localhost port=5432 user=otus password=otus dbname=calendar sslmode=disable" up

generate:
	go generate ./...

up:
	docker-compose -f .docker/docker-compose.yml up

down:
	docker-compose -f .docker/docker-compose.yml down

.PHONY: build